name = "Daisy SMP Modpack"
author = "macuguita"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "846ce84519a3a5b120f1a2f3ecf428da6382dd53682eb80e969cf0ed4f3a0534"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
datapack-folder = "resources/datapack/required"
