name = "Daisy SMP Modpack"
author = "macuguita"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca78c67dca50bcd5295f7795b992edc1cfefa6b6d03f288ad5245086df9cf0b4"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
datapack-folder = "resources/datapack/required"
