name = "Daisy Create"
author = "macuguita"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a250eba0829748242c89e471157052ae69920a0fb7b17112f3b7e0901c48c59e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "resources/common/required"
